.code

GC_MALLOC_INLINE[private]:
NAME(0,"size") TSTORE_I4(0)
TLOAD_I4(0) GC_MALLOC_FAST TSTORE_R(1) TLOAD_R(1)
BRANCH_T(0) 
TLOAD_I4(0) GC_MALLOC_CALL TSTORE_R(1)
TARGET(0) TLOAD_R(1);

GC_SAFE_INLINE[private]:
;

