.code

GC_MALLOC_INLINE[private]:
NAME(0,"size") TSTORE_U4(0)
TLOAD_U4(0) GC_MALLOC_FAST TSTORE_R(1) TLOAD_R(1)
BRANCH_T(0) 
TLOAD_U4(0) GC_MALLOC_CALL TSTORE_R(1)
TARGET(0) 
TLOAD_R(1) TLOAD_U4(0) __ZERO_MEMORY
TLOAD_R(1);

GC_SAFE_INLINE[private]:
    ADDR(gvmt_gc_waiting) PLOAD_I4 IF GC_SAFE_CALL ENDIF 
;

GC_ALLOC_ONLY_INLINE[private]:NAME(0,"size") TSTORE_U4(0)
TLOAD_U4(0) GC_MALLOC_FAST TSTORE_R(1) TLOAD_R(1)
BRANCH_T(0) 
TLOAD_U4(0) GC_MALLOC_CALL TSTORE_R(1)
TARGET(0) 
TLOAD_R(1);

