#define YOUNG_SPACE 1
#define NOT_MOVING_SPACE 2
#define MATURE_SPACE 4
#define LARGE_SPACE 8

#define UNUSED_SPACE 0
#define NURSERY_SPACE YOUNG_SPACE
#define PINNED_SPACE (YOUNG_SPACE | NOT_MOVING_SPACE)
#define SURVIVOR_SPACE_1 (YOUNG_SPACE | 16)
#define SURVIVOR_SPACE_2 (YOUNG_SPACE | 32)
#define SURVIVOR_SPACE_3 (YOUNG_SPACE | 48)

#define is_young_space(s) ((s)&YOUNG_SPACE)
#define LARGE_OBJECT_SPACE (YOUNG_SPACE | NOT_MOVING_SPACE | LARGE_SPACE)

